### ISSUE TITLE
.net error doesn't load camera configs on vers 1.67

### ISSUE THREAD

**Issue by Turnipisum** [gentlepumpkin/bi-aidetection#37]
See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.InvalidOperationException: Invoke or BeginInvoke cannot be called on a control until the window handle has been created.
   at System.Windows.Forms.Control.MarshaledInvoke(Control caller, Delegate method, Object[] args, Boolean synchronous)
   at System.Windows.Forms.Control.Invoke(Delegate method, Object[] args)
   at WindowsFormsApp2.Shell.IncrementErrorCounter()
   at WindowsFormsApp2.Shell.<Log>d__22.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_0(Object state)

**Comment by NikolasKomonen** [comment]
Just started having this issue as well. I've had it up and running before for a couple days but then I woke up to this error.

**Comment by NikolasKomonen** [comment]
@Turnipisum hey I solved my issue. I think it was because I deleted the default camera profile. If you extract the zip again and copy the defaut.txt file into the existing folder then it might work again.
